### ISSUE TITLE
No Null Protection

### ISSUE THREAD

**Issue by byBlurr** [wochilly/quannet#44]
The bot has no NULL protection. This means if a channel that is in the database gets deleted, it will not check if it actually exists. When messaging all the channels, if a channel is deleted, it can cause the bot to crash or stop responding.

**Comment by wochilly** [comment]
Unfortunately, this is a real issue in the Hack Week submission version, as there are no events to handle deleted channels/guilds. In later versions, if a channel/guild is deleted, their entries in the database will be cleaned up.
